export const PAGE_TITLES = {
  home: 'Início',
  progress: 'Minha evolução',
  workouts: 'Treinos',
  workoutForm: 'Cadastro de treino',
  settings: 'Configurações',
  clients: 'Pessoas',
  client: 'Cliente',
  students: 'Alunos',
  student: 'Aluno',
  studentNotFound: 'Aluno não encontrado',
  foodDiary: 'Diário Alimentar',
  professionals: 'Buscar profissional',
  professionalProfile: 'Perfil do profissional',
  nutritionistMirror: 'Minha nutricionista',
  educatorMirror: 'Meu educador físico',
  messages: 'Mensagens',
  messageThread: 'Conversa',
  scheduling: 'Agenda',
  schedulingBook: 'Agendar horário',
} as const;
